#! /data/data/com.termux/usr/bin/bash
bersih
echo -e " \ e [1; 35m
L) ## S) ssss h) l) L l) L  
L) S) ss h) \ e [1; 93ml) l)  
L) o) OOO g) GGG i) n) NNNN S) ss \ e [1; 32mh) HHHH e) EEEEE l) l)  
L) o) OO g) GG i) n) NN S) h) \ e [1; 96mHH e) EEEE l) l)  
L) o) OO g) GG i) n) NN S) ss h) HH e) l) l)  
L) lllll o) OOO g) GGGG i) n) NN S) ssss h) HH e) EEEE l) LL l) LL 
                      GG                                                  
                 g) GGGG                                                   
\ e [1; 35m
[+] Penulis: D3XPL0IT3R
[+] Tim: PLAKOR SQUAD
[+] Github: https://github.com/D3XPLOIT3R
\ e [0m "
baca -p $ ' \ e [31mBuat Nama Pengguna Untuk Login: \ e [0m ' username
baca -p $ ' \ e [32mBuat Password Untuk Login: \ e [0m ' password
CD 
cd ..
cd usr / etc
rm motd
rm bash.bashrc
cat << LOGIN> bash.bashrc
perangkap '' 2
echo -e "\ e [1; 32m
                ──▄▀▀▀▄───────────────
                Please Login To Continue Your Termux
                ──█───█───────────────
                ─███████─────────▄▀▀▄─
                ░██─▀─██░░█▀█▀▀▀▀█░░█░
                ░███▄███░░▀░▀░░░░░▀▀░░
\ e [0m "
baca -p $ '\ e [32mUSERNAME: \ e [0m' pengguna
read -s -p $ '\ e [32mPASSWORD: \ e [0m' pass
if [[\ $ pass == $ password && \ $ user == $ username]]; kemudian
PS1 = '\ 033 [1; 32m
\ a┏ \ a \ 033 [1; 32m
\ a┏ \ a━ \ a┃ Terminal Profesional Anda - ┃ \ @ ┃ --- | \ d ┃
\ a \ a┃ \ a \ a \ 033 [1; 32jt $ pengguna ━┛ \ 033 [1; 36m
\ a┗ \ a┳ \ a━ \ a📂 \ 033 [1; 32m \ w \ a📂
┗ DEXPL0IT3R@ '
shopt -s autocd
shopt -s cdspell
shopt -s checkhash
shopt -s checkwinsize
shopt -s compat31
shopt -s compat32
shopt -s compat40
shopt -s compat41
shopt -s no_empty_cmd_completion
shopt -s histverify
shopt -s histappend
shopt -s dirspell
shopt -s direxpand
shopt -s compat43
shopt -s compat32
shopt -s lithist
lain
echo ""
echo -e "\ e [1; 31m Kata Sandi Anda Salah
Sampai jumpa:) \ e [0m "
tidur 3
keluar
fi
perangkap 2
GABUNG
echo -e "\ e [1; 32m Tampilan Shell Sudah Dirubah, Keluar Termux Lalu Masuk Kembalj \ e [0m"
